apiVersion: apps/v1        
kind: Deployment           
metadata:
  name: connectify-record-service  
spec:
  replicas: 3              # Expected number of Pod replicas
  selector:                
    matchLabels:           
      app: connectify-record   
  template:                # Pod template
    metadata:              
      labels:             
        app: connectify-record 
    spec:                            # Pod specification
      containers:                    # Container list
        - name: connectify-record        # Container name 
          image: cyvqet/connectify:v1.0  # Container image
          ports:            
            - containerPort: 8080    # Container listening port
          env:                        # Environment variables
            - name: ENV              # Environment type
              value: "k8s"           # Use k8s environment
          resources:
            requests:            # Container startup resources
              memory: "256Mi"    # Minimum memory: 256Mi
              cpu: "250m"        # Minimum CPU: 250m
            limits:              # Container runtime resources
              memory: "512Mi"    # Maximum memory: 512Mi
              cpu: "500m"        # Maximum CPU: 500m